# Generated by Django 3.2.4 on 2021-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتابها'},
        ),
        migrations.AlterField(
            model_name='book',
            name='public_year',
            field=models.DateTimeField(verbose_name='year of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='record_Date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time to record books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
    ]
