# Generated by Django 3.2.4 on 2021-06-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210625_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='public_year',
            new_name='publish_year',
        ),
    ]
